-- require('lint').linters_by_ft = {
--   markdown = {'vale',}
-- }
-- au BufWritePost * lua require('lint').try_lint()
-- vim.api.nvim_create_autocmd({ "BufWritePost" }, {
--   callback = function()
--     require("lint").try_lint()
--   end,
-- })
